### ISSUE TITLE
SEUS PTGI slow light calcs

### ISSUE THREAD

**Issue by STH-FrolDIST** [daipenger/minema#14]
Path tracing feature looks _ghostly_ in final result. Character moves with regular speed but light/shadow covers him too slow. Speed of light is slow in comparison with it should be in exported video. Seems like it doesn't sync light calc to other visual.

Just look at some moments there's "ghost" effect:
https://youtu.be/P8Rx1xjjRW4?t=401

**Comment by mchorse** [comment]
That's just the way PTGI works in general. I think I have an idea how to "fix" this. I'll try adding an option to Minema a bit later once I'll clean up some stuff.

**Comment by mchorse** [comment]
Implemented, we'll be available once I release it (or in dev-builds).
