### ISSUE TITLE
Feature Request: Built-in 360° equirectangular recording option

### ISSUE THREAD

**Issue by RYRY1002** [daipenger/minema#18]
The title pretty much says it all. Ideally, it would be something similar to the Replay Mod's implementation of 360° equirectangular recording. This would be ideal for someone like me who needs to record a ~2-hour high quality 360° video. This would also remove the artifact of screen space reflections when you combine 6 square videos, and would drastically lower recording times. It would also make it far easier for the average user to record 360° videos with Minema, as most users won't know how to combine 6 videos and stitch them up perfectly, nevermind if the 6 recordings are slightly out of time and therefor ruin the immersion, which won't happen if it's built-in.

If there is already a way to do this (that isn't recording the same thing 6 times then stitching them all together) I'd love to know about it.
Thanks.

**Comment by mchorse** [comment]
If you know how it can be implemented, feel free to try implementing yourself, because I don't know how to render a cube map.

**Comment by RYRY1002** [comment]
> If you know how it can be implemented, feel free to try implementing yourself, because I don't know how to render a cube map.

Ok, I don't either I was just wondering if any of you devs know how to. Maybe daipenger does?

**Comment by mchorse** [comment]
@RYRY1002 this was added by @NyaNLI in the [just released update](https://github.com/daipenger/minema/releases/tag/v3.6-ShaderSync). 🥳
