### ISSUE TITLE
Minema does something weird when changing the resolution

### ISSUE THREAD

**Issue by ReComplexed** [daipenger/minema#21]
1. I have changed the resolution in Minema to 4k in the config Files with Forge
2. I have allocated FFMpeg in the config Files with FIrge
3. I have changed my minecraft to fullscreen (Otherwise it would say an Error)

4. I have started the recording with F4

- Minecraft showed me a small box with my Minecraft World, but the other things like my keystrokes and Hotbar Slots were Tiny

- **Normal Recording works**
- **Increased FPS Workes**
- Increased 4x Screenshots with OptiFine works

- **I have a GTX 750 Ti like it was made with the demo Video**
- I have  more Mods: McLib, Aperture (I was intending to make 4K Vidos for me any my friends), OreLib Support Library, Dynamic Surroundings, Fancy Block Particles, LabyMod, Mo' Bends, Sound Physics, Dynamic  Surroundings: HUDs, OptiFine
- Every Mod Works and  they only make the Sound or the Graphics Better, so it would be nice to keep them

![-](https://user-images.githubusercontent.com/67727916/111168448-5c059d00-85a2-11eb-9b5a-837eaa033898.png)
This Photo is not recorded in 4K but in Full HD (I have 2 1440x900 Monitors in use)

**Comment by mchorse** [comment]
This happens due to some Optifine option like fast render or Antialiasing in shaders options. You need to disable those. 

If it still happens, try enabling Fix fast render and antialiasing option in Minema’s Capturing mod options.

**Comment by ReComplexed** [comment]
Thanks! It worked now. I had Antialising on 4x...
