### ISSUE TITLE
PNG format in minema

### ISSUE THREAD

**Issue by rojaoo** [daipenger/minema#25]
Hi, I wanna use the mod in image sequence mode, bug tga is too large. How did i select another image format, like png or jpeg?

**Comment by mchorse** [comment]
> Hi, I wanna use the mod in image sequence mode, bug tga is too large. How did i select another image format, like png or jpeg?

You’ll need to change Encoder arguments to something like: 

```
-f rawvideo -pix_fmt bgr24 -s %WIDTH%x%HEIGHT% -r %FPS% -i - -vf %DEFVF% %NAME%_%d.png
```

**Comment by rojaoo** [comment]
But i'll still be needing the ffmpeg. I'm on Android, the reason for me to use the image sequence is because i can't install ffmpeg. In older versions of the mod it had the option to change the image format, like jpg, png, gif...

**Comment by mchorse** [comment]
> But i'll still be needing the ffmpeg. I'm on Android, the reason for me to use the image sequence is because i can't install ffmpeg. In older versions of the mod it had the option to change the image format, like jpg, png, gif...

Oh... then there is no other way, sorry. 😔

There was a way to export pngs instead of tag indeed, but for some reason it got removed.

**Comment by rojaoo** [comment]
Well, at least you tried to help me, thank you!
