### ISSUE TITLE
In-game speed and video playback speed

### ISSUE THREAD

**Issue by flowwas** [daipenger/minema#26]
Just wondering how this works. I'm recording at 60fps with all settings set to default except for the export AE camera turned on. I'm normally reaching around 160fps in-game. When I record, the game gets super fast. Like, 3 times faster or something. But the exported video plays at normal speed. When I turn off synchronization in the mod settings, the in-game speed is normal but then the video plays too slow instead. The higher my framerate is, the faster the game is. Is this normal behavior? What can I do to have the game play at normal speed AND have the video play at normal speed? It's really difficult to get a sense of time when the game isn't playing at the right speed. Thanks!

**Comment by mchorse** [comment]
@zxnny yeah, if you record with Minema for gameplay stuff, it will be hard to keep track of time. It sounds like your computer is pretty powerful and it records at the speed it can record. I have a couple of tips, but I'm not sure whether it will work in your case:

1. Enable Show overlay option, after Minema 3.5.4 it doesn't appear in the video, so you can keep track of the time by looking at the Real Time section in the bottom left corner.
2. If the game runs too fast, try increasing Capturing > Held frames to a higher number until you're comfortable to record with. If you're not using Minema 3.6, I'd recommend updating it, as it Held frames option had issues with synchronization which NyaNLI fixed in 3.6.
3. If you don't do fancy GUI stuff during recording, or interacting with modded content, you can try out using Blockbuster's [first person playback](https://youtu.be/ioHMMEhxgkE?t=157).

**Comment by ghost** [comment]
Sounds like you need the frame rate limiting option, I'll try to add it when I have time.

**Comment by flowwas** [comment]
@mchorse Thanks for the suggestions! I think I'll try your 3rd tip, should work for what I'm doing. Just another thing though while you're here, you're probably the right person to ask. Are there any ways to get recorded Minecraft camera movement into 3D software, like Blender for example? Other than motion tracking it of course. I'm working on a relatively difficult shot that I plan to bring into Blender and do fluid simulations with, so motion tracking will (probably) be possible but will also be very tedious and time consuming. I know there's Minema's AE camera export feature that I mentioned and it's possible to bring that into Blender with an add-on but I couldn't get it to work. The Minecraft to AE part, I mean. Can you explain how this is done correctly? My intention is to place a 3D solid/plane on a block that I got the coordinates of by using the /clone command in-game. When I've pasted the keyframe data to the camera and changed the MFS setting to Vertically it looks like it should (I think?) until I add in a 3D solid and copy the block coordinates to it. That's when it looks like this: https://www.youtube.com/watch?v=Xnu2zosDcbg
The block I'm trying to stick it to is on the tree I'm circling around (second block from the ground). Got any ideas? The scale of the solid seems very off too because no matter if it's set to 1, 100 or 1000, adding a grid effect to it doesn't even make out a grid pattern at all, it just looks like it's zoomed in to the point where it's just showing a corner of it or something.

**Comment by mchorse** [comment]
@NyaNLI implemented this feature, I honestly don’t know how it works, but hopefully NyaNLI would be able to explain it.

**Comment by ghost** [comment]
Could you please provide this video and tracking data so I can test what the problem is.

**Comment by flowwas** [comment]
Sure, this is a different video since I deleted the other one (didn't think I'd need it) but I'm having the same issue with this one, so. I'm trying to place a solid on an invisible block (it's at 171 91 21) in the middle of that big frame/opening. Here's a GDrive link.
https://drive.google.com/file/d/1NJGhTQeCnAMTmSgtFgjaQxJD6DvuAeUS/view?usp=sharing

**Comment by ghost** [comment]
After I tested it, it looks like the tracking data is correct, and I noticed that you didn't describe whether you have the camera set to "One-Node Camera", which could be the reason for your incorrect tracking results.


https://user-images.githubusercontent.com/20377926/125719739-7adcb3b8-f828-4f22-b058-5b23fb18e125.mp4

**Comment by flowwas** [comment]
Perfect, that was indeed the problem. Thanks! Closing the issue now :)
