### ISSUE TITLE
The action of walking looks weird from the video rendered by Minema

### ISSUE THREAD

**Issue by ASH1260081144** [daipenger/minema#32]
Uploading 2021-10-16_22.55.25.mp4…

I feel sorry to tell you about that. It looks normal in the aperture, while after using Minema, the walking of the character looks weird.

**Comment by mchorse** [comment]
Looks like you didn’t let video uploaded and pressed comment, so I can’t see the video. 😂

However, yes, the walking around would look weird as Minema’s way of recording will introduces a lot of variable lag during recording. You should use Aperture’s manual fixture to record yourself walking, and then record it with Minema (if you need just the camera movement).

If you’ll ever experience the `32768` issue, watch this: https://www.youtube.com/watch?v=96_VnqywyRY&t=239s
