### ISSUE TITLE
Most likely never, unless someone else will pick up the project.

### ISSUE THREAD

**Issue by HakkaTjakka** [daipenger/minema#34]
Most likely never, unless someone else will pick up the project.

_Originally posted by @mchorse in https://github.com/daipenger/minema/issues/22#issuecomment-845163287_

Then why you start something but don't update it on newer versions?
You know ReplayMod sucks really hard and is a real bummer compared to the synchronized in game rendering. 
Its because the 1.12.2 version of MC also sucks compared to the newer versions. Its not updated and its full of trash code and bugs.

The only good thing about MC was the recording with Minema mod in combination with the Bauercam mod.

Why create something knowing newer versions will come out of MC when not adapting it to these newer versions.
Thank god i'm not a java programmer, because Windows is shit (that is why i switched to Linux), Java is shit, MC is shit, its all shitty software compared to the real games that work smoothly because its professional. 
Also the console and Windows 10 versions suck.

Well, the whole world sucks.
Anyway thanks for the experience on 1.12.2

Me myself also have written a lot of code in c/c++ with internal ffmpeg player functions and use of external ffmpeg for input and output. If you know the thrill it is very easy but like i said i'm discussed of Java and all the versioning shit, with almost 100.000 mods avail, Forge, Fabric versions, server versions.
Its just a pile of trash.

Have a good life.

**Comment by mchorse** [comment]
If you don't like it so much, fork Minetest, or even make your own voxel sandbox. If everything is so shitty, why don't you do anything about it?

**Comment by Chryfi** [comment]
40 years of c++ programming experience you say? You act like a script kiddie. If java is so shitty, stop complaining here, you have no idea how much work mods like Minema, Blockbuster etc. are and how much time it costs to update them.
Act like a grown up, or simply be quiet.
