### ISSUE TITLE
how can i use it on Android？

### ISSUE THREAD

**Issue by northgreen** [daipenger/minema#40]
I am using pojavluncher，But I don't know how to fix the FFmpeg below this.

**Comment by mchorse** [comment]
You need to install ffmpeg for video recording to work. I don't know if there are any binaries for Android, so unless you can find a working binary for Android, this issue can't be fixed. 😔

**Comment by northgreen** [comment]
> You need to install ffmpeg for video recording to work. I don't know if there are any binaries for Android, so unless you can find a working binary for Android, this issue can't be fixed. 😔

I have tried to compile ffmpeg on Android myself, but I have encountered a permission problem. It seems that this problem is really unsolvable unless root has his own mobile phone.😂😂😂

**Comment by northgreen** [comment]
Or does this mod record an intermediate file and render it with a computer? （🤔）

**Comment by mchorse** [comment]
> Or does this mod record an intermediate file and render it with a computer? （🤔）

Minema can render video to tga if Video encoding is disabled, but you would still need to somehow put these tgas together into a video file. I don't know how you would do it without `ffmpeg`.
