### ISSUE TITLE
[Question] Does 1.13 work for this?

### ISSUE THREAD

**Issue by NJDaeger** [daipenger/minema#7]

**Comment by mchorse** [comment]
No, because there are no 1.13 releases. I really doubt that daipenger would update it to 1.13.

**Comment by daipenger** [comment]
Forge had a major, major rewrite with 1.13. From my perspective that was certainly needed but also means that minema now needs a by far larger update than previous versions. Basically every class from the 1.12 codebase breaks right now.

I will gladly accept and audit any pull requests if someone updates it. Once my free time permits it I will do it myself but I cannot tell when that's going to happen.
