### ISSUE TITLE
Recorded video goes faster than expectation

### ISSUE THREAD

**Issue by sorae42** [daipenger/minema#9]
After I stopped and view the recording, I noticed the video play so much faster than I expected.

Demo video: https://youtu.be/fk8SokdpfD8

Settings: 1920x1080 90FPS
Other settings are in its default state.

**Comment by mchorse** [comment]
Did you recorded this on a dedicated server? If you did, that's why it didn't work. In other case, check that engine synchronization is enabled in Mod Options > Minema > Engine overrides (I don't remember exact name, but something like that).

**Comment by sorae42** [comment]
Nope, it was a singleplayer world. And Engine Overrides is enabled too. (E.O. seems to be turned on by default.)

**Comment by mchorse** [comment]
Hm... it's weird. Are you sure it's not YouTube's issue? Because YouTube shows that the video is at 48 FPS instead of 90FPS. Try recording a 60FPS video and play it in VLC instead of default video viewer app on your OS.

**Comment by sorae42** [comment]
VLC, Sony Vegas, After Effects have the same problem.
I have to slow down the video before I could edit.

**Comment by sorae42** [comment]
And yeah, 60 FPS also make the video goes fast.
Only 30 FPS works, but that's what I'm not intended.

**Comment by mchorse** [comment]
Could you copy and paste here the encoder args in the Encoding category? Mine is this (it's default value for that config option):

```
-f rawvideo -pix_fmt bgr24 -s %WIDTH%x%HEIGHT% -r %FPS% -i - -vf vflip -c:v libx264 -preset ultrafast -tune zerolatency -qp 18 -pix_fmt yuv420p %NAME%.mp4
```

Take the note of `-r %FPS%`, this is what determines the correct FPS. Make sure it's not just `-r 30` 😅

**Comment by sorae42** [comment]
Cool, thanks a lot, I'll close the issue if it has solved.

**Comment by sorae42** [comment]
It doesn't work, still giving the same, faulty result.

**Comment by mchorse** [comment]
Then pastebin/gist the `minem.cfg` file. Also, which version of ffmpeg do you use? (maybe you could also pastebin one of the .log files from the `movies` folder?)

**Comment by sorae42** [comment]
minema.cfg: https://pastebin.com/7knwz14j
Recent log: https://pastebin.com/b4Vw4uYN

**Comment by mchorse** [comment]
You had engine speed set to `3.0` (which means the video will be 3 times as fast)... 🤦‍♂ 

```
D:engineSpeed=3.0
```

Change it to `1.0`, and everything should work fine. 😅

**Comment by daipenger** [comment]
Thanks @mchorse for clearing that up 😄

**Comment by mchorse** [comment]
@daipenger no problem! 👍

**Comment by sorae42** [comment]
Turns out the problems come from the "CMDCam" mod. The mod doesn't want to sync with Minema so that's why I have such problem.
I tested it with `D:engineSpeed=1.0` with modified FFmpeg parameters and It works! (just doing normal stuff)

( I think I need suggestion on Smooth Camera Movement for Cinematic Scene, maybe I should increase the camera movement time?)

**Comment by daipenger** [comment]
@deilias 
CMDCam runs its camera path in real time. You need something that ignores the frametimes and just does one step at each frame.

You can either use my [BauerCam](https://github.com/daipenger/BauerCam/releases) (The latest version should also run with 1.12.2) or @mchorse 's [Aperture](https://www.curseforge.com/minecraft/mc-mods/aperture).

My minecraftforum page was deleted, so BauerCam doesn't have a manual right now. (Yeah, I should really fill the README file again) But in a nutshell, the keys 'j', 'k' and 'l' roll the camera, 'u', 'i' and 'o' change the field of view and 'p' creates a point. The rest is done by using '/cam'. It's a fairly simple and small mod.
Aperture on the other hand can do a bit more (and has a guide) 😅 So your choice all depends on the kind of features you need.

**Comment by mchorse** [comment]
I would recommend BauerCam as it's much easier to use and pretty much as simple as CMDCam/PixelCam/CamStudio. 🙂 

But if you need very complex camera work, then check out Aperture (but mind that it has a steep learning curve). 😉

**Comment by sorae42** [comment]
Thanks a lot guys!
